---
version: "2"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    volumes:
      - ~/sync/config:/config
      - ~/Downloads/t/downloads:/config/Downloads
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
