"set ttymouse=xterm2
"set background=dark
"set t_Co=256
colorscheme koehler

" Map to clear last search
nmap <SPACE> <SPACE>:noh<CR>
nmap <F8> :TagbarToggle<CR>
nnoremap <F7> :NERDTreeToggle<CR>

Bundle 'dgryski/vim-godef'
Bundle 'xolox/vim-misc'
Bundle 'vim-colorscheme-switcher'

"UnBundle 'easymotion/vim-easymotion'

let g:colorscheme_switcher_define_mappings = 0
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
"let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
let g:syntastic_json_checkers = ['jsonlint']
let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_check_on_open = 1
let g:syntastic_auto_jump = 0
let g:gofmt_command="goimports"
"let JSHintUpdateWriteOnly=1
"let g:JSHintHighlightErrorLine = 0
let g:airline_powerline_fonts=1
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

function! ToggleErrors()
  if empty(filter(tabpagebuflist(), 'getbufvar(v:val, "&buftype") is# "quickfix"'))
    " No location/quickfix list shown, open syntastic error location panel
    Errors
  else
    lclose
  endif
endfunction
nnoremap <F6> :call ToggleErrors()<CR>
