source ~/workspace/sh/tools/etc/vimrc

set ttymouse=xterm2
set background=dark
"set t_Co=256

" Map to clear last search
nmap <SPACE> <SPACE>:noh<CR>
nmap <F8> :TagbarToggle<CR>
nnoremap <F7> :NERDTreeToggle<CR>

Plugin 'dgryski/vim-godef'
Plugin 'syntaxcomplete'
"Plugin 'othree/html5.vim' " Suporte para html5 tags e atributes
"Plugin 'wookiehangover/jshint.vim'
Plugin 'tpope/vim-fugitive' " Allow to use git in vim
Plugin 'phleet/vim-mercenary' " Allow to use mercurial in vim
Plugin 'kchmck/vim-coffee-script' " Plugin to edit coffeescript files
"Plugin 'elzr/vim-json' " JSON formater
Plugin 'chase/vim-ansible-yaml' " Yaml 
Plugin 'maksimr/vim-jsbeautify' "Plugin to format js

"colorscheme mophiaDark
"colorscheme guardian
"colorscheme molokai
"colorscheme solarized
colorscheme jiks

let g:syntastic_json_checkers = ['jsonlint']

"let g:syntastic_html_checkers = ['w3']
let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_check_on_open = 1
let g:syntastic_auto_jump = 0
let g:gofmt_command="goimports"
"let JSHintUpdateWriteOnly=1
"let g:JSHintHighlightErrorLine = 0
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }
let g:default_java_workspace="~/workspace/java"

function! ToggleErrors()
  if empty(filter(tabpagebuflist(), 'getbufvar(v:val, "&buftype") is# "quickfix"'))
    " No location/quickfix list shown, open syntastic error location panel
    Errors
  else
    lclose
  endif
endfunction
nnoremap <F6> :call ToggleErrors()<CR>
