#!/bin/bash

#Gocode
go get -u -v github.com/nsf/gocode
go install -v github.com/nsf/gocode

#Goimport
go get -u -v golang.org/x/tools/
go install -v golang.org/x/tools/cmd/goimports

#Godef
go get -u -v github.com/rogpeppe/godef
go install -v github.com/rogpeppe/godef

#Gotags
go get -u -v github.com/jstemmer/gotags
go install -v github.com/jstemmer/gotags

#Golint
go get -u -v github.com/golang/lint
go install -v github.com/golang/lint

#GoConvey
go get -u -v github.com/smartystreets/goconvey
go install -v github.com/smartystreets/goconvey

#GoTTy
go get -u -v github.com/yudai/gotty
go install github.com/yudai/gotty

#Whenchange
go get -u -v ronoaldo.gopkg.net/whenchange
go install -v ronoaldo.gopkg.net/whenchange

#Aeremote
go get -u -v ronoaldo.gopkg.net/aetools/aeremote
go install -v ronoaldo.gopkg.net/aetools/aeremote
